name: Burrow VPN Server

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install deps
        run: pip install aioice rich requests
      
      - name: Setup config
        run: |
          mkdir -p ~/.burrow
          echo '{"dav":"${{ secrets.YA_LOGIN }}:${{ secrets.YA_PASSWORD }}"}' > ~/.burrow/config.json
      
      - name: Run server
        run: timeout 21590 python burrow.py -s
